name: Sync README to Docker Hub

on:
  push:
    paths:
      - 'README.md'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: robrosa/speedtest-net
          readme-filepath: ./README.md
          short-description: ${{ github.event.repository.description }}
